kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: awes-logs
  namespace: was
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: awes-nodefiles
  namespace: was
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi