#!/bin/bash
# AWS Setup Script
# July-2023



cd ~/wolfram/WAS-Kubernetes/EnvironmentSetup/AWS/Source/terraform

cd kubernetes
echo "building AWS VPC and EKS Cluster. Takes around 15 minutes..."
terraform init
terraform apply -var-file=../queriumcorp.tfvars
cd ..

echo "Deploying WAS prerequisites ...."

cd kubernetes_vpa
echo "deploying Kubernetes Vertical Pod Autoscaler"
terraform init
terraform apply -var-file=../queriumcorp.tfvars

cd kubernetes_metricsserver
echo "deploying Kubernetes Metrics Server"
terraform init
terraform apply -var-file=../queriumcorp.tfvars
cd ..

cd kubernetes_prometheus
echo "deploying Kubernetes Prometheus"
terraform init
terraform apply -var-file=../queriumcorp.tfvars
cd ..

cd kubernetes_cert_manager
echo "deploying Kubernetes Certificate Manager"
terraform init
terraform apply -var-file=../queriumcorp.tfvars
cd ..

cd kubernetes_ingress_controller
echo "deploying Kubernetes Ingress Controller"
terraform init
terraform apply -var-file=../queriumcorp.tfvars
cd ..

cd kubernetes_minio
echo "deploying Kubernetes Minio"
terraform init
terraform apply -var-file=../queriumcorp.tfvars
cd ..

cd kubernetes_kafka
echo "deploying Kubernetes Kafka"
terraform init
terraform apply -var-file=../queriumcorp.tfvars
cd ..

cd kubernetes_was
echo "Deploying WAS"
terraform init
terraform apply -var-file=../queriumcorp.tfvars
cd ..
