#!/bin/bash
# AWS Setup Script
# July-2023

AWS_ACCOUNT=320713933456
AWS_REGION=us-east-1
AWS_DYNAMODB_TABLE="terraform-state-locking-was2"
AWS_S3_BUCKET="${AWS_ACCOUNT}-terraform-tfstate-was-01"

# Create required Terraform state resources
aws dynamodb create-table --region $AWS_REGION --table-name $AWS_DYNAMODB_TABLE --attribute-definitions AttributeName=LockID,AttributeType=S --key-schema AttributeName=LockID,KeyType=HASH --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1
aws s3api create-bucket --bucket $AWS_S3_BUCKET --region $AWS_REGION

# Build and deploy
echo "building AWS VPC and EKS Cluster and deploying WAS. Takes around 30 minutes..."

cd ~/wolfram/WAS-Kubernetes/EnvironmentSetup/AWS/Source/terraform/was
terraform init
terraform apply
cd ..

