#!/bin/bash
# AWS Teardown Script
# July-2023


# Build and deploy
echo "Destroying AWS resources. Takes around 5 minutes..."

cd ~/wolfram/WAS-Kubernetes/EnvironmentSetup/AWS/Source/terraform/was
terraform init
terraform destroy
cd ..

# Create required Terraform state resources
aws dynamodb create-table --region $AWS_REGION --table-name $AWS_DYNAMODB_TABLE --attribute-definitions AttributeName=LockID,AttributeType=S --key-schema AttributeName=LockID,KeyType=HASH --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1
aws s3api create-bucket --bucket $AWS_S3_BUCKET --region $AWS_REGION

