default_language_version:
  # default language version for each language
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # See https://pre-commit.com/hooks.html for more hooks
      - id: check-added-large-files
        args: ['--maxkb=2048']
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
     # - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: destroyed-symlinks
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: pretty-format-json
     # - id: check-yaml
        exclude: |
            (?x)^(
                EnvironmentSetup/Azure^|
                EnvironmentSetup/AWS-legacy^
            )$
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.22 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      - id: terraform-fmt
      - id: helmlint
      - id: terraform-validate
      - id: terragrunt-hclfmt
      - id: tflint
     # - id: shellcheck
      - id: yapf
      - id: markdown-link-check
        exclude: |
            (?x)^(
                EnvironmentSetup/Azure^|
                EnvironmentSetup/AWS-legacy^|
                EnvironmentSetup/AWS/README.md
            )$
