# see: https://stackoverflow.com/questions/70075203/how-to-use-volume-gp3-in-storage-class-on-eks
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer