---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: awesrestartpods
subjects:
- kind: ServiceAccount
  name: awesrestartpods
  namespace: was
roleRef:
  kind: Role
  name: awesrestartpods
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: awesrestartpods
  namespace: was
  labels:
    k8s-app: was-awes
rules:
- apiGroups: ["apps"]
  resources:
  - deployments 
  verbs:
  - patch
  - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: awesrestartpods
  namespace: was
  labels:
    k8s-app: was-awes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: endpoint-manager-deployment
  namespace: was
  labels:
    app: endpoint-manager
spec:
  selector:
    matchLabels:
      app: endpoint-manager
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: endpoint-manager
    spec:
      serviceAccountName: awesrestartpods
      restartPolicy: Always
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        - name: LOG_LOCATION
          value: /opt/app/logs
        - name: KAFKA.BOOTSTRAP-SERVERS
          value: kafka-persistent-kafka-bootstrap.kafka.svc.cluster.local:9092
        image: wolframapplicationserver/endpoint-manager:1.2.1
        name: endpoint-manager
        ports:
        - containerPort: 8085
        resources:
          limits:
            cpu: "1000m"
            memory: 1Gi
          requests:
            cpu: "500m"
            memory: 500Mi
        readinessProbe:
          tcpSocket:
            port: 8085
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8085
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - mountPath: "/opt/app/logs"
          name: endpoint-logs-storage
      initContainers:
      - name: init-minio
        image: bash
        command: ["bash", "-c", "for i in $(seq 1 3000); do nc -zvw1 minio 9000 && exit 0 || sleep 3; done; exit 1"]
      - name: init-kafka
        image: bash
        command: ["bash", "-c", "for i in $(seq 1 3000); do nc -zvw1 kafka-persistent-kafka-bootstrap.kafka.svc.cluster.local 9092 && exit 0 || sleep 3; done; exit 1"]
      - name: init-kafka-resources-topic
        image: bash
        command: ["bash", "-c", "apk --update add curl; set -x; while true; do response=$(curl -s kafka-bridge-service.kafka.svc.cluster.local:9092/topics); if [[ ${response} =~ .*\"resource-info\".* ]]; then break; else sleep 5; fi; done" ]
      - name: init-kafka-endpoints-topic
        image: bash
        command: ["bash", "-c", "apk --update add curl; set -x; while true; do response=$(curl -s kafka-bridge-service.kafka.svc.cluster.local:9092/topics); if [[ ${response} =~ .*\"endpoint-info\".* ]]; then break; else sleep 5; fi; done" ]
      - name: init-kafka-nodefiles-topic
        image: bash
        command: ["bash", "-c", "apk --update add curl; set -x; while true; do response=$(curl -s kafka-bridge-service.kafka.svc.cluster.local:9092/topics); if [[ ${response} =~ .*\"nodefile-info\".* ]]; then break; else sleep 5; fi; done" ]
      - name: init-resource-manager
        image: bash
        command: ["bash", "-c", "for i in $(seq 1 3000); do nc -zvw1 resource-manager 9090 && exit 0 || sleep 3; done; exit 1"]
      volumes:
        - name: endpoint-logs-storage
          persistentVolumeClaim:
            claimName: endpoint-logs
